#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'

cookbook 'ntp',
  :git => 'git://github.com/opscode-cookbooks/ntp.git'

#cookbook 'cassandra'
cookbook 'java'

cookbook 'nginx'

cookbook 'graphite',
	:git => 'https://github.com/hw-cookbooks/graphite'
