#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'

cookbook 'ntp',
  :git => 'git://github.com/opscode-cookbooks/ntp.git'

#cookbook 'graphite',
#  :git => 'https://github.com/hectcastro/chef-graphite'

#cookbook 'statsd',
#  :git => 'https://github.com/hectcastro/chef-statsd'

#cookbook 'nodejs',
#  :git => 'https://github.com/hectcastro/chef-nodejs'

cookbook 'graphite',
	:git => 'https://github.com/hw-cookbooks/graphite'