# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-server-12.10"
  config.vm.box_url = "http://grahamc.com/vagrant/ubuntu-12.04.2-i386-chef-11-omnibus.box"
  config.cache.auto_detect = true

  config.vm.define :proxy do |proxy|
    proxy.vm.hostname = 'proxy'
    proxy.vm.network :forwarded_port, guest:   80, host: 8081
    proxy.vm.network :private_network, ip: "33.33.33.1"
    proxy.vm.provider "virtualbox" do |v|
      v.name = 'Proxy'
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50", "--memory", "256"]
    end
    proxy.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = [ "cookbooks", "site-cookbooks" ]
      chef.add_recipe "apt"
      chef.add_recipe "ntp"
      chef.add_recipe "ha-cloud"    
      chef.json = {
        :nginx => {
          :gzip => 'on',
          :gzip_http_version => '1.1'
        } 
      }
    end
  end

  config.vm.define :gateway do |gateway|
    gateway.vm.hostname = 'proxy'
    gateway.vm.network :forwarded_port, guest: 8082, host: 8082   # REST API
    gateway.vm.network :private_network, ip: "33.33.33.11"
    gateway.vm.provider "virtualbox" do |v|
      v.name = 'Gateway'
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50", "--memory", "256"]
    end
    gateway.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = [ "cookbooks", "site-cookbooks" ]
      chef.add_recipe "apt"
      chef.add_recipe "ntp"
      chef.add_recipe "ha-gateway"
      chef.json = {
        :java => {
          :jdk_version  => '7',
          :install_flavor => 'oracle',
          :oracle => {
            :accept_oracle_download_terms => 'true'
          }
        }
      }
    end
  end

  config.vm.define :cassandra1 do |cassandra1|
    cassandra1.vm.network :forwarded_port, guest:  9160, host:  9160  # rpc port
    cassandra1.vm.network :forwarded_port, guest:  7000, host:  7000  # storage port
    #cassandra1.vm.network :forwarded_port, guest: 12345, host: 12345  # jmx_dash port
    cassandra1.vm.provider "virtualbox" do |v|
      v.name = 'Cassandra - Node 1'
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50", "--memory", "1024"]
    end
    cassandra1.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = [ "cookbooks", "site-cookbooks" ]
      chef.add_recipe "cassandra::datastax"
      chef.json = {
        :cassandra => {
          :cluster_name => 'test',
          :vnodes => '256',
          :java_heap_size_max => '1024',
          :java_heap_size_eden => '1024'
        },
        :java => {
          :jdk_version  => '6',         # Datastax recommends usage of Java 6!
          :install_flavor => 'oracle',
          :oracle => {
            :accept_oracle_download_terms => 'true'
          }
        }
      }
    end
  end

  config.vm.define :graphite do |graphite|
    graphite.vm.hostname = 'monitoring'
    #graphite.vm.network :forwarded_port, guest:   80, host: 8081  # Graphite webapp
    graphite.vm.network :forwarded_port, guest: 2003, host: 2003  # Carbon port
    graphite.vm.network :private_network, ip: "33.33.33.99"
    graphite.vm.provider "virtualbox" do |v|
      v.name = 'Graphite'
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50", "--memory", "512"]
    end
    graphite.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = [ "cookbooks", "site-cookbooks" ]
      #chef.roles_path = "../my-recipes/roles"
      #chef.data_bags_path = "../my-recipes/data_bags"
      #chef.add_recipe "mysql"
      #chef.add_role "web"
      chef.add_recipe "apt"
      chef.add_recipe "ntp"
      chef.add_recipe "graphite"    
      chef.json = {
        :graphite => {
          :carbon => {
            :line_receiver_interface => '10.0.2.15',
            :pickle_receiver_interface => '10.0.2.15',
            :cache_query_interface => '10.0.2.15'
          },
          #:web => {
          #  :admin_email => 'admin@whatever.com'
          #}
        }
      }
    end
  end

end
